name: Labeler

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.3.0
        with:
          skip-delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
